"""ScoreMosaic Ensemble canonical, comparison, report, and evaluation contracts."""

from .canonical import (
    CanonicalEvent,
    CanonicalMeasure,
    CanonicalModelError,
    CanonicalPart,
    CanonicalScore,
    DivisionsChange,
    EventProvenance,
    NormalizationDiagnostic,
    Pitch,
    SourceIdentity,
    TabPosition,
    TimeSignature,
    TimeSignatureChange,
    TimingMovement,
    TupletRatio,
)
from .comparator import (
    COMPARISON_FORMAT_VERSION,
    CandidateObservation,
    CandidateSummary,
    ComparisonDifference,
    ComparisonError,
    ComparisonLocation,
    ComparisonResult,
    compare_candidates,
)
from .evaluation import (
    CORE_METRIC_NAMES,
    DATASET_SCHEMA_VERSION,
    DATASET_TYPE,
    METRIC_NAMES,
    RESULT_SCHEMA_VERSION,
    RESULT_TYPE,
    EvaluationError,
    EvaluationResult,
    MetricResult,
    evaluate_candidate,
    load_fixed_dataset,
    validate_evaluation_result_payload,
    validate_fixed_dataset,
)
from .musicxml import MusicXmlNormalizationError, normalize_musicxml
from .report import (
    REPORT_SCHEMA_VERSION,
    REPORT_TYPE,
    ComparisonReportError,
    EnsembleComparisonReport,
    build_comparison_report,
    validate_comparison_report_payload,
)

__all__ = [
    "COMPARISON_FORMAT_VERSION",
    "CORE_METRIC_NAMES",
    "DATASET_SCHEMA_VERSION",
    "DATASET_TYPE",
    "METRIC_NAMES",
    "REPORT_SCHEMA_VERSION",
    "REPORT_TYPE",
    "RESULT_SCHEMA_VERSION",
    "RESULT_TYPE",
    "CandidateObservation",
    "CandidateSummary",
    "CanonicalEvent",
    "CanonicalMeasure",
    "CanonicalModelError",
    "CanonicalPart",
    "CanonicalScore",
    "ComparisonDifference",
    "ComparisonError",
    "ComparisonLocation",
    "ComparisonReportError",
    "ComparisonResult",
    "DivisionsChange",
    "EnsembleComparisonReport",
    "EvaluationError",
    "EvaluationResult",
    "EventProvenance",
    "MetricResult",
    "MusicXmlNormalizationError",
    "NormalizationDiagnostic",
    "Pitch",
    "SourceIdentity",
    "TabPosition",
    "TimeSignature",
    "TimeSignatureChange",
    "TimingMovement",
    "TupletRatio",
    "build_comparison_report",
    "compare_candidates",
    "evaluate_candidate",
    "load_fixed_dataset",
    "normalize_musicxml",
    "validate_comparison_report_payload",
    "validate_evaluation_result_payload",
    "validate_fixed_dataset",
]

__version__ = "0.3.0"
