"""ScoreMosaic Ensemble canonical, comparison, convergence, report, and evaluation contracts."""

from .admission import (
    ADMISSION_FORMAT_VERSION,
    CandidateAdmissionError,
    CanonicalAdmissionEvidence,
    CanonicalCandidateInput,
    EnsembleAdmissionResult,
    admit_and_compare_candidates,
)
from .canonical import (
    CanonicalEvent,
    CanonicalMeasure,
    CanonicalModelError,
    CanonicalPart,
    CanonicalScore,
    DivisionsChange,
    EventProvenance,
    NormalizationDiagnostic,
    Pitch,
    SourceIdentity,
    TabPosition,
    TimeSignature,
    TimeSignatureChange,
    TimingMovement,
    TupletRatio,
)
from .comparator import (
    COMPARISON_FORMAT_VERSION,
    CandidateObservation,
    CandidateSummary,
    ComparisonDifference,
    ComparisonError,
    ComparisonLocation,
    ComparisonResult,
    compare_candidates,
)
from .convergence import (
    CANDIDATE_CONVERGENCE_HANDOFF_VERSION,
    CONVERGENCE_FORMAT_VERSION,
    CandidateConvergenceError,
    ConvergenceCandidateInput,
    Stage7ConvergenceResult,
    converge_verified_candidates,
    parse_verified_candidate_handoff,
)
from .evaluation import (
    CORE_METRIC_NAMES,
    DATASET_SCHEMA_VERSION,
    DATASET_TYPE,
    METRIC_NAMES,
    RESULT_SCHEMA_VERSION,
    RESULT_TYPE,
    EvaluationError,
    EvaluationResult,
    MetricResult,
    evaluate_candidate,
    load_fixed_dataset,
    validate_evaluation_result_payload,
    validate_fixed_dataset,
)
from .musicxml import MusicXmlNormalizationError, normalize_musicxml
from .report import (
    REPORT_SCHEMA_VERSION,
    REPORT_TYPE,
    ComparisonReportError,
    EnsembleComparisonReport,
    build_comparison_report,
    validate_comparison_report_payload,
)

__all__ = [
    "ADMISSION_FORMAT_VERSION",
    "CANDIDATE_CONVERGENCE_HANDOFF_VERSION",
    "COMPARISON_FORMAT_VERSION",
    "CONVERGENCE_FORMAT_VERSION",
    "CORE_METRIC_NAMES",
    "DATASET_SCHEMA_VERSION",
    "DATASET_TYPE",
    "METRIC_NAMES",
    "REPORT_SCHEMA_VERSION",
    "REPORT_TYPE",
    "RESULT_SCHEMA_VERSION",
    "RESULT_TYPE",
    "CandidateAdmissionError",
    "CandidateConvergenceError",
    "CandidateObservation",
    "CandidateSummary",
    "CanonicalAdmissionEvidence",
    "CanonicalCandidateInput",
    "CanonicalEvent",
    "CanonicalMeasure",
    "CanonicalModelError",
    "CanonicalPart",
    "CanonicalScore",
    "ComparisonDifference",
    "ComparisonError",
    "ComparisonLocation",
    "ComparisonReportError",
    "ComparisonResult",
    "ConvergenceCandidateInput",
    "DivisionsChange",
    "EnsembleAdmissionResult",
    "EnsembleComparisonReport",
    "EvaluationError",
    "EvaluationResult",
    "EventProvenance",
    "MetricResult",
    "MusicXmlNormalizationError",
    "NormalizationDiagnostic",
    "Pitch",
    "SourceIdentity",
    "Stage7ConvergenceResult",
    "TabPosition",
    "TimeSignature",
    "TimeSignatureChange",
    "TimingMovement",
    "TupletRatio",
    "admit_and_compare_candidates",
    "build_comparison_report",
    "compare_candidates",
    "converge_verified_candidates",
    "evaluate_candidate",
    "load_fixed_dataset",
    "normalize_musicxml",
    "parse_verified_candidate_handoff",
    "validate_comparison_report_payload",
    "validate_evaluation_result_payload",
    "validate_fixed_dataset",
]

__version__ = "0.4.0"
