"""ScoreMosaic OMR Gateway foundation and disabled contract libraries."""

from .artifact_lifecycle import (
    ARTIFACT_STATES,
    CANDIDATE_STATES,
    LIFECYCLE_CONTRACT_TYPE,
    LIFECYCLE_SCHEMA_VERSION,
    OUTPUT_ARTIFACT_KINDS,
    ArtifactLifecycleError,
    ArtifactRecord,
    CandidateArtifactLifecycle,
    CandidateRecord,
    LifecycleEvent,
    build_artifact_lifecycle,
    transition_artifact,
    transition_candidate,
    verify_artifact_lifecycle,
)
from .filename_safety import (
    SafeIntakeFilenameError,
    validate_original_filename,
)
from .orchestration import (
    ACCEPTED_SOURCE_MEDIA_TYPES,
    ENGINE_NAMES,
    ORCHESTRATION_CONTRACT_TYPE,
    ORCHESTRATION_SCHEMA_VERSION,
    EngineRunPlan,
    ExpectedArtifactPlan,
    GatewayOrchestrationPlan,
    OrchestrationContractError,
    SourceArtifactPlan,
    build_orchestration_plan,
    verify_orchestration_plan,
)
from .safe_intake import (
    SAFE_INTAKE_MEDIA_TYPES,
    SAFE_INTAKE_POLICY_V1,
    SAFE_INTAKE_POLICY_VERSION,
    ImageInspectionResult,
    SafeIntakeByteBudgetError,
    SafeIntakeFormat,
    SafeIntakeImageError,
    SafeIntakeMediaTypeError,
    SafeIntakePdfError,
    SafeIntakePolicy,
    SafeIntakeSignatureError,
    SignatureMatch,
    inspect_image_pixels,
    inspect_pdf_pages,
    match_input_signature,
    measure_input_bytes,
    verify_signature_media_type,
)

__all__ = [
    "ACCEPTED_SOURCE_MEDIA_TYPES",
    "ARTIFACT_STATES",
    "CANDIDATE_STATES",
    "ENGINE_NAMES",
    "LIFECYCLE_CONTRACT_TYPE",
    "LIFECYCLE_SCHEMA_VERSION",
    "ORCHESTRATION_CONTRACT_TYPE",
    "ORCHESTRATION_SCHEMA_VERSION",
    "OUTPUT_ARTIFACT_KINDS",
    "SAFE_INTAKE_MEDIA_TYPES",
    "SAFE_INTAKE_POLICY_V1",
    "SAFE_INTAKE_POLICY_VERSION",
    "ArtifactLifecycleError",
    "ArtifactRecord",
    "CandidateArtifactLifecycle",
    "CandidateRecord",
    "EngineRunPlan",
    "ExpectedArtifactPlan",
    "GatewayOrchestrationPlan",
    "ImageInspectionResult",
    "LifecycleEvent",
    "OrchestrationContractError",
    "SourceArtifactPlan",
    "SafeIntakeByteBudgetError",
    "SafeIntakeFilenameError",
    "SafeIntakeFormat",
    "SafeIntakeImageError",
    "SafeIntakeMediaTypeError",
    "SafeIntakePdfError",
    "SafeIntakePolicy",
    "SafeIntakeSignatureError",
    "SignatureMatch",
    "build_artifact_lifecycle",
    "build_orchestration_plan",
    "inspect_image_pixels",
    "inspect_pdf_pages",
    "match_input_signature",
    "measure_input_bytes",
    "transition_artifact",
    "transition_candidate",
    "validate_original_filename",
    "verify_artifact_lifecycle",
    "verify_orchestration_plan",
    "verify_signature_media_type",
    "__version__",
]

__version__ = "0.3.0"
